_wandb:
    value:
        cli_version: 0.22.2
        e:
            w1l0x607t2xtk3ryo8uivjdwibyge1bj:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "12884901888"
                args:
                    - --rom
                    - ms_pacman
                    - --total_frames
                    - "1000000"
                    - --wandb_project
                    - physical-atari
                    - --checkpoint_interval
                    - "100000"
                codePath: sim_dqn_latency.py
                codePathLocal: sim_dqn_latency.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "602940522496"
                email: praneetkedari38@gmail.com
                executable: /Users/praneetkedari/anaconda3/envs/physical_atari/bin/python
                git:
                    commit: ec89e946795438a1b2ae54366b90fe8c65a1a0b0
                    remote: https://github.com/lakers38/physical_atari.git
                host: Praneets-Typewriter-2.local
                memory:
                    total: "17179869184"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/praneetkedari/Documents/GitHub/physical_atari/sim_dqn_latency.py
                python: CPython 3.11.14
                root: /Users/praneetkedari/Documents/GitHub/physical_atari
                startedAt: "2025-10-23T22:52:55.331109Z"
                writerId: w1l0x607t2xtk3ryo8uivjdwibyge1bj
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 61
            "4": 3.11.14
            "5": 0.22.2
            "10":
                - 20
            "12": 0.22.2
            "13": darwin-arm64
batch_size:
    value: 32
buffer_size:
    value: 100000
checkpoint_interval:
    value: 100000
checkpoint_name:
    value: dqn_sim.pt
delay_frames:
    value: 6
epsilon_decay_frames:
    value: 1000000
epsilon_end:
    value: 0.1
epsilon_start:
    value: 1
gamma:
    value: 0.99
latency_weights:
    value: latency_wrap
learning_rate:
    value: 0.00025
no_latency:
    value: false
obs_height:
    value: 84
obs_width:
    value: 84
results_dir:
    value: results/sim_dqn
rom:
    value: ms_pacman
seed:
    value: 0
stack_size:
    value: 4
target_update_freq:
    value: 10000
total_frames:
    value: 1000000
train_freq:
    value: 4
train_start:
    value: 50000
wandb_entity:
    value: null
wandb_project:
    value: physical-atari
wandb_run_name:
    value: null
