_wandb:
    value:
        cli_version: 0.22.2
        e:
            8zt4m4s4q859bps1jyx7l5wxmi9mq0wa:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "9663676416"
                args:
                    - --agent_type
                    - agent_dqn
                    - --rom
                    - ms_pacman
                    - --total_frames
                    - "300_000"
                    - --checkpoint_interval
                    - "10_000"
                    - --record_video
                    - --video_dir
                    - videos/dqn_ms_pacman
                    - --video_every
                    - "10"
                    - --wandb_project
                    - physical-atari-dqn
                    - --wandb_run_name
                    - dqn_ms_pacman_latency
                codePath: sim_latency.py
                codePathLocal: sim_latency.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "602394796032"
                email: praneetkedari38@gmail.com
                executable: /Users/praneetkedari/anaconda3/envs/physical_atari/bin/python
                git:
                    commit: 4047f30333ed8ac20716ce90b02a5c18298d5460
                    remote: https://github.com/lakers38/physical_atari.git
                host: Praneets-Typewriter-2.local
                memory:
                    total: "17179869184"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/praneetkedari/Documents/GitHub/physical_atari/sim_latency.py
                python: CPython 3.11.14
                root: /Users/praneetkedari/Documents/GitHub/physical_atari
                startedAt: "2025-10-27T16:00:06.437605Z"
                writerId: 8zt4m4s4q859bps1jyx7l5wxmi9mq0wa
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.22.2
            "10":
                - 20
            "12": 0.22.2
            "13": darwin-arm64
agent_type:
    value: agent_dqn
checkpoint_interval:
    value: 10000
checkpoint_name:
    value: sim_agent.pt
delay_frames:
    value: 6
latency_weights:
    value: latency_wrap
load_model:
    value: null
log_interval:
    value: 10000
no_latency:
    value: false
no_wandb:
    value: false
record_video:
    value: true
results_dir:
    value: /Users/praneetkedari/Documents/GitHub/physical_atari/results/sim_latency
rom:
    value: ms_pacman
seed:
    value: 0
total_frames:
    value: 300000
video_dir:
    value: videos/dqn_ms_pacman
video_every:
    value: 10
video_fps:
    value: 60
wandb_entity:
    value: null
wandb_project:
    value: physical-atari-dqn
wandb_run_name:
    value: dqn_ms_pacman_latency
